platform :ios, '12.0' # Version minimale iOS requise

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'tt_wifi3' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])

    # Exclure arm64 pour les simulateurs (si nécessaire pour M1/M2)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
